### ISSUE TITLE
Buildscripts: Integrate clang-tidy

### ISSUE THREAD

**Issue by diagprov** [teserakt-io/libe4#16]
Integrate and add clang-tidy as part of the build process, and report errors.

**Comment by diagprov** [comment]
This is blocked on the inclusion of clang-tidy into github actions (see https://github.com/actions/virtual-environments/issues/357) or some other workaround. The necessary work is done our side: running:

    make tidy

Invokes the `clang-tidy` tool if present (and fails if not).

**Comment by daeMOn63** [comment]
@diagprov shall we create our own github action running from a docker container with just this tool in it ?

**Comment by diagprov** [comment]
Whoops, this shouldn't have been closed. I have created a small container for this purpose and it is now integrated in develop.
I might try to make this a better action if I can.
